DEFAULT_REDIS_CHECKPOINT_TTL_SECONDS = 6 * 60 * 60
DEFAULT_REDIS_MAX_CHECKPOINTS_PER_THREAD = 15
DEFAULT_REDIS_REFRESH_TTL_ON_READ = True
DEFAULT_REDIS_SOCKET_TIMEOUT = 5.0
DEFAULT_REDIS_SOCKET_CONNECT_TIMEOUT = 5.0
DEFAULT_REDIS_HEALTH_CHECK_INTERVAL = 30
DEFAULT_REDIS_RETRY_ON_TIMEOUT = True
